name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install FFTW and GSL
      run: |
        sudo apt-get update
        sudo apt-get install -y libfftw3-dev libgsl-dev
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      name: default build
      with:
        command: build
        args: --all-targets
    - uses: actions-rs/cargo@v1
      name: build GSL + static FFTW
      with:
        command: build
        args: --all-targets --features gsl,fftw-source --no-default-features
    - uses: actions-rs/cargo@v1
      name: build GSL + dynamic FFTW
      with:
        command: build
        args: --all-targets --features gsl,fftw-system --no-default-features
    - uses: actions-rs/cargo@v1
      name: build GSL + MKL
      with:
        command: build
        args: --all-targets --features gsl,fftw-mkl --no-default-features

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install FFTW and GSL
      run: |
        sudo apt-get update
        sudo apt-get install -y libfftw3-dev libgsl-dev
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: test

  test-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install FFTW and GSL
        run: |
          sudo apt-get update
          sudo apt-get install -y libfftw3-dev libgsl-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release

  examples:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install FFTW and GSL
      run: |
        sudo apt-get update
        sudo apt-get install -y libfftw3-dev libgsl-dev
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: run
        args: --example plot_snia_curve_fits -- -n=1

  fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install FFTW and GSL
      run: |
        sudo apt-get update
        sudo apt-get install -y libfftw3-dev libgsl-dev
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets -- -D warnings

  arm:

    runs-on: [self-hosted, linux, ARM64]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: build
      run: cargo build --all-targets
